### ISSUE TITLE
Redirecting page  to Home

### ISSUE THREAD

**Issue by HilkiahDev** [MufidJamaluddin/Codeigniter4-HMVC#13]
Every time I try to add module and try to access the route, it always redirect me to the Home page. please enlighten me in the issue, thanks

**Comment by MufidJamaluddin** [comment]
> Every time I try to add module and try to access the route, it always redirect me to the Home page. please enlighten me in the issue, thanks

I apologize for late response. I apologize for late responding. In this HMVC, if you use command to generate the module, you could see the routes settings.

If you go to `/admin`, you will call the `Dashboard::index`. If you go to `/admin/awards`, you will call the `Awards::index`. Please uniquely define the path.

![image](https://user-images.githubusercontent.com/28973632/210128464-b640b364-7d3a-4325-9523-97e471f2ec7e.png)
