### ISSUE TITLE
Error Kint\Renderer\Renderer after first instalation

### ISSUE THREAD

**Issue by lukman-ss** [MufidJamaluddin/Codeigniter4-HMVC#14]
after i added new module get error when php spark serve

Edit
updated
Change This

app/Config/Kint.php has been updated for Kint 5.0. You need to replace Kint\Renderer\Renderer with Kint\Renderer\AbstractRenderer and replace Renderer::SORT_FULL with AbstractRenderer::SORT_FULL.
source: https://forum.codeigniter.com/showthread.php?tid=86106

**Comment by lukman-ss** [comment]
updated
Change This

app/Config/Kint.php has been updated for Kint 5.0. You need to replace Kint\Renderer\Renderer with Kint\Renderer\AbstractRenderer and replace Renderer::SORT_FULL with AbstractRenderer::SORT_FULL.
source: https://forum.codeigniter.com/showthread.php?tid=86106

**Comment by MufidJamaluddin** [comment]
Terima kasih mas Lukman atas informasi-nya terkait update.

**Comment by MufidJamaluddin** [comment]
I'm so sorry. Please downgrade to CodeIgniter 4.2.
