### ISSUE TITLE
The application environment is not set correctly.

### ISSUE THREAD

**Issue by YogX15** [MufidJamaluddin/Codeigniter4-HMVC#17]
When I updated composer, suddenly an error like this appeared

Warning: Use of undefined constant ENVIRONMENT - assumed 'ENVIRONMENT' (this wil
l throw an Error in a future version of PHP) in C:\laragon\www\ltrtrs\vendor\cod
eigniter4\framework\system\CodeIgniter.php on line 583

Warning: Cannot modify header information - headers already sent by (output star
ted at C:\laragon\www\ltrtrs\vendor\codeigniter4\framework\system\CodeIgniter.ph
p:583) in C:\laragon\www\ltrtrs\vendor\codeigniter4\framework\system\CodeIgniter
.php on line 587
![Screenshot 2023-09-10 232743](https://github.com/MufidJamaluddin/Codeigniter4-HMVC/assets/43494957/20ffc313-3ae3-4816-9638-bb6b418f668e)

**Comment by MufidJamaluddin** [comment]
I'm so sorry. Please downgrade to CodeIgniter 4.2.
