### ISSUE TITLE
vendor/codeigniter4 ... failed to open stream

### ISSUE THREAD

**Issue by panpic** [MufidJamaluddin/Codeigniter4-HMVC#2]
I am error following:
Warning: require(C:\xampp\htdocs\study\codeigniter\4hmvc\app\Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in C:\xampp\htdocs\study\codeigniter\4hmvc\public\index.php on line 36

I do not see folder: "vendor/codeigniter4....". How do I get there ?

Thanks & Regards

**Comment by pioneersingh321** [comment]
try composer update command on your root

**Comment by MufidJamaluddin** [comment]
> I am error following:
> Warning: require(C:\xampp\htdocs\study\codeigniter\4hmvc\app\Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in C:\xampp\htdocs\study\codeigniter\4hmvc\public\index.php on line 36
> 
> I do not see folder: "vendor/codeigniter4....". How do I get there ?
> 
> Thanks & Regards


> try composer update command on your root
