### ISSUE TITLE
Failed load vendor ...

### ISSUE THREAD

**Issue by panpic** [MufidJamaluddin/Codeigniter4-HMVC#7]
Warning: require(C:\xampp\htdocs\study\codeigniter\4hmvc\app\Config/../../vendor/codeigniter4/framework/system/bootstrap.php): failed to open stream: No such file or directory in C:\xampp\htdocs\study\codeigniter\4hmvc\public\index.php on line 36

**Comment by MufidJamaluddin** [comment]
Hi @panpic, please install the dependency first.
